FROM haproxy:2.8

USER root

RUN apt-get update && apt-get install -y keepalived iproute2 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY start.sh /start.sh
RUN chmod +x /start.sh

CMD ["/start.sh"]