networks:
  otus-net:
    external: true

volumes:
  etcd1-data:
  etcd2-data:
  etcd3-data:

services:
  etcd1:
    image: quay.io/coreos/etcd:v3.4.26
    container_name: etcd1
    networks:
      otus-net:
        ipv4_address: 10.10.0.21
    environment:
      ETCDCTL_API: "3"
    command: [
      "etcd",
      "--name=etcd1",
      "--data-dir=/etcd-data",
      "--listen-peer-urls=http://0.0.0.0:2380", 
      "--listen-client-urls=http://0.0.0.0:2379",
      "--advertise-client-urls=http://10.10.0.21:2379",
      "--initial-advertise-peer-urls=http://10.10.0.21:2380",
      "--initial-cluster=etcd1=http://10.10.0.21:2380,etcd2=http://10.10.0.22:2380,etcd3=http://10.10.0.23:2380",
      "--initial-cluster-state=new",
      "--initial-cluster-token=etcd-cluster-1",
      "--enable-v2=true"
    ]
    volumes:
      - etcd1-data:/etcd-data
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 5s
      timeout: 10s
      retries: 5

  etcd2:
    image: quay.io/coreos/etcd:v3.4.26
    container_name: etcd2
    networks:
      otus-net:
        ipv4_address: 10.10.0.22
    environment:
      ETCDCTL_API: "3"
    command: [
      "etcd",
      "--name=etcd2",
      "--data-dir=/etcd-data",
      "--listen-peer-urls=http://0.0.0.0:2380",
      "--listen-client-urls=http://0.0.0.0:2379", 
      "--advertise-client-urls=http://10.10.0.22:2379",
      "--initial-advertise-peer-urls=http://10.10.0.22:2380",
      "--initial-cluster=etcd1=http://10.10.0.21:2380,etcd2=http://10.10.0.22:2380,etcd3=http://10.10.0.23:2380",
      "--initial-cluster-state=new",
      "--initial-cluster-token=etcd-cluster-1",
      "--enable-v2=true"
    ]
    volumes:
      - etcd2-data:/etcd-data
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 5s
      timeout: 10s
      retries: 5

  etcd3:
    image: quay.io/coreos/etcd:v3.4.26
    container_name: etcd3
    networks:
      otus-net:
        ipv4_address: 10.10.0.23
    environment:
      ETCDCTL_API: "3"
    command: [
      "etcd",
      "--name=etcd3", 
      "--data-dir=/etcd-data",
      "--listen-peer-urls=http://0.0.0.0:2380",
      "--listen-client-urls=http://0.0.0.0:2379",
      "--advertise-client-urls=http://10.10.0.23:2379",
      "--initial-advertise-peer-urls=http://10.10.0.23:2380",
      "--initial-cluster=etcd1=http://10.10.0.21:2380,etcd2=http://10.10.0.22:2380,etcd3=http://10.10.0.23:2380",
      "--initial-cluster-state=new",
      "--initial-cluster-token=etcd-cluster-1",
      "--enable-v2=true"
    ]
    volumes:
      - etcd3-data:/etcd-data
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 5s
      timeout: 10s
      retries: 5

  # Patroni nodes
  patroni1:
    image: patroni:17.6
    container_name: patroni1
    networks:
      otus-net:
        ipv4_address: 10.10.0.11
    volumes:
      - ./patroni1.yml:/etc/patroni.yml:ro
      - ./data/postgres1:/mnt/data
    user: "postgres"
    depends_on:
      etcd1:
        condition: service_healthy
      etcd2:
        condition: service_healthy
      etcd3:
        condition: service_healthy

  patroni2:
    image: patroni:17.6
    container_name: patroni2
    networks:
      otus-net:
        ipv4_address: 10.10.0.12
    volumes:
      - ./patroni2.yml:/etc/patroni.yml:ro
      - ./data/postgres2:/mnt/data
    user: "postgres"
    depends_on:
      etcd1:
        condition: service_healthy
      etcd2:
        condition: service_healthy
      etcd3:
        condition: service_healthy

  patroni3:
    image: patroni:17.6
    container_name: patroni3
    networks:
      otus-net:
        ipv4_address: 10.10.0.13
    volumes:
      - ./patroni3.yml:/etc/patroni.yml:ro
      - ./data/postgres3:/mnt/data
    user: "postgres"
    depends_on:
      etcd1:
        condition: service_healthy
      etcd2:
        condition: service_healthy
      etcd3:
        condition: service_healthy

  # HAProxy nodes
  haproxy1:
    image: haproxy:2.8
    container_name: haproxy1
    networks:
      otus-net:
        ipv4_address: 10.10.0.31
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

  haproxy2:
    image: haproxy:2.8
    container_name: haproxy2
    networks:
      otus-net:
        ipv4_address: 10.10.0.32
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

  # Keepalived nodes
  keepalived1:
    image: osixia/keepalived:2.0.20
    container_name: keepalived1
    networks:
      otus-net:
        ipv4_address: 10.10.0.35
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./keepalived/keepalived1.conf:/usr/local/etc/keepalived/keepalived.conf:ro

  keepalived2:
    image: osixia/keepalived:2.0.20
    container_name: keepalived2
    networks:
      otus-net:
        ipv4_address: 10.10.0.36
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./keepalived/keepalived2.conf:/usr/local/etc/keepalived/keepalived.conf:ro