scope: postgres-cluster
namespace: /db/

name: patroni1

restapi:
  listen: 0.0.0.0:8008
  connect_address: 10.10.0.11:8008

etcd:
  hosts: 10.10.0.21:2379,10.10.0.22:2379,10.10.0.23:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 100
        shared_buffers: 128MB
        dynamic_shared_memory_type: posix
        max_wal_senders: 10
        max_replication_slots: 10
        wal_level: replica
        hot_standby: on
        archive_mode: on
        archive_command: "/bin/true"

  initdb:
  - encoding: UTF8
  - data-checksums

  pg_hba:
  - host replication replicator 10.10.0.0/24 md5
  - host all all 0.0.0.0/0 md5

postgresql:
  listen: 0.0.0.0:5432
  connect_address: 10.10.0.11:5432
  data_dir: /mnt/data
  pgpass: /tmp/pgpass
  authentication:
    replication:
      username: replicator
      password: replicator123
    superuser:
      username: postgres
      password: postgres123
  parameters:
    unix_socket_directories: '.'

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
